### ISSUE TITLE
Possible to provide a prebuilt version in releases?

### ISSUE THREAD

**Issue by SubhrajyotiSen** [blenderskool/untab#12]
Right now I would have to download the project, get dependencies and built the project before using it. 
It would be really helpful if a prebuilt version is available as a GitHub release.

**Comment by blenderskool** [comment]
That's a great idea, we don't have a CI set up right now so I'll be manually adding the built project as a release.

**Comment by blenderskool** [comment]
@SubhrajyotiSen This is done! Check the prerelease here https://github.com/blenderskool/untab/releases/tag/v0.0.1
