### ISSUE TITLE
Remove margin when title is not present

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#19]
Webpage titles are absent in some rare cases and in those cases, the URL has a margin at the top. This margin should not be there and the URL should be vertically aligned center with respect to the favicon.

![image](https://user-images.githubusercontent.com/21107799/94330245-675b1100-ffe0-11ea-98b5-240148b7e3ac.png)

**Comment by i-aryan** [comment]
Hey, I can work it out for you. Assign, please.

**Comment by blenderskool** [comment]
Sure go ahead @i-aryan

**Comment by i-aryan** [comment]
I've made a PR for the issue. Please review it.

**Comment by blenderskool** [comment]
Closed via #22
