### ISSUE TITLE
Pluralize results text based on the results count

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#29]
The total results count shown is not pluralized correctly and it shows `1 results` instead of `1 result` when there is only one result found.

![image](https://user-images.githubusercontent.com/21107799/96339856-bf070c80-10b4-11eb-86f3-49659db5d2b5.png)

**Comment by rajivnayanc** [comment]
Hey, this seems like a quick fix. I can do it. Assign me this task.

**Comment by rajivnayanc** [comment]
![image](https://user-images.githubusercontent.com/31794134/96348001-55422f00-10c3-11eb-8439-794c42da56ee.png)

After building the code, the extension manager shows the above error. Was not even able to run it on my system.

**Comment by blenderskool** [comment]
Just for records,
> After building the code, the extension manager shows the above error. Was not even able to run it on my system.

_This error was fixed along with this issue_
