### ISSUE TITLE
A new blue theme

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#34]
A blue theme(suggest a better name!) for UnTab. Here's a small preview of what it can look like
_Note: Colors may not be exact, as an image with the spearmint theme was photoshopped to get this!_

![](https://user-images.githubusercontent.com/21107799/97084334-d6557500-1633-11eb-84fb-131ea2554c20.jpg)

**Comment by MatusSkerlik** [comment]
I would like to work on this, could you assign it to me ?

**Comment by blenderskool** [comment]
Sure @MatusSkerlik. Make sure to go through the CONTRIBUTING guide.
