### ISSUE TITLE
A .new shortcuts plugin

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#35]
`.new` domain is used for various shortcuts on the internet. Maybe we can create a plugin called `new-shortcuts` that has a **small set** of common productivity tools listed here https://whats.new/shortcuts

This plugin can be accessed by doing `/new` and then typing the name of the shortcut.

**Comment by MatusSkerlik** [comment]
I will lovely work on this if you assign it to me.

**Comment by blenderskool** [comment]
@MatusSkerlik It would be great if new contributors can pick up this issue, maybe you can work on some other issue? 🙂

**Comment by Gurvir-Sandhar** [comment]
Can I take this issue?

**Comment by blenderskool** [comment]
@Gurvir-Sandhar Sure, please go ahead.

**Comment by blenderskool** [comment]
Closed via #74
