### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#4]
All features currently work on Firefox except for the favicons. Favicons cannot be accessed in Firefox extensions, so some changes would be needed for it.

**Comment by radiantly** [comment]
Hey,

Great extension idea, love it!

I tried loading the extension using about:debugging on firefox, but it doesn't seem to work. Does the favicon code need to be removed in order for basic functionality to work?

Firefox 80.0.1 for Manjaro Linux

**Comment by blenderskool** [comment]
Hi @radiantly,

I had tested it with Firefox 80.0.1 and it seems to work (except the favicons). Make sure you follow the steps below to test it on Firefox:
- First build the project by running `npm run build` in the root directory.
- Load the extension using `about:debugging` by selecting `Load Temporary Add-on...`. In the file browser, choose the manifest file generated in `dist` folder after the build process in previous step.

**Comment by blenderskool** [comment]
Issues remaining to resolve for complete Firefox support:
- [X] missing favicons in tabs
- [ ] missing favicons/fallback icon in history and bookmarks
- [ ] history and tabs not listed in the first open of extension, need to type some characters to see the list.

**Comment by radiantly** [comment]
In the meantime, could the extension be added to the Firefox addon store?

**Comment by blenderskool** [comment]
@radiantly Yes, I would love to add it to the respective browser stores. We just need a logo for extension #13 to make that happen!

**Comment by blenderskool** [comment]
@radiantly UnTab just got published in the Firefox add-on store! Check it out here https://addons.mozilla.org/en-US/firefox/addon/view-untab/
