### ISSUE TITLE
Interesting Violet theme with orange accents

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#46]
Inspired by this theme https://rainglow.io/preview/#horizon on Rainglow, here's a similar theme for UnTab.
Feel free to suggest a name for this theme.

![](https://user-images.githubusercontent.com/21107799/97804966-1c848700-1c79-11eb-93b3-2156c2139e85.png)

_Note: Colors need not be exact, as above picture was created as a reference._

**Comment by TheVamster** [comment]
How about Midnight with a moon?

**Comment by TheVamster** [comment]
How about 'Midnight' with a '🌙 ' emoji?

**Comment by blenderskool** [comment]
@TheVamster Emoji can be something else as it's similar to the `Dark` theme we already have

**Comment by tanishqvyas** [comment]
@blenderskool How about `Lamentis Theme` with the emoji `☄️` as a nod to the `Loki : Episode 3`

**Comment by blenderskool** [comment]
@tanishqvyas I'm good with it 🙂

**Comment by tanishqvyas** [comment]
@blenderskool Thanks. Please proceed then : )

**Comment by blenderskool** [comment]
Decided to go with `Lamentis`. I like how the colors of this theme match the episode so well!

Thanks, @vamsikoneti, @tanishqvyas, @Gurvir-Sandhar for suggestions 😄 

![](https://user-images.githubusercontent.com/21107799/139554585-32eba0b0-23a5-410b-8a12-03ede3bd7a84.png)
