### ISSUE TITLE
Open URL in a new tab plugin

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/untab#5]
A plugin that would open the typed URL in the input in a new tab.

**Comment by asharonbaltazar** [comment]
Isn't this the current behavior?

**Comment by blenderskool** [comment]
@asharonbaltazar No, right now it would just search for tab/history whose URL _matches_ the user's query.  
I was wondering if a feature can be added that can match URLs like `github.com` and show `Open github.com in a new tab` in the result (irrespective of whether a tab/history was found matching this url).  

I think it is possible with a plugin.

**Comment by asharonbaltazar** [comment]
Do you have a specific plugin in mind? I can try figuring this out.

**Comment by blenderskool** [comment]
Sure go ahead!

**Comment by radiantly** [comment]
Hi, I could take a shot at this if no one else is working on it?

**Comment by blenderskool** [comment]
Sure @radiantly
