### ISSUE TITLE
A hot-key / button to close tabs right from the untab window

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#53]
Currently unTab shows the search results for all the currently opened tabs but there is no provision to close the tabs right from the unTab window itself. We have to go to the respective window and either close it with the cursor or use ```ctrl+w``` or make use of tab actions (which closes only the currently open tab). 

If there would be a hot-key or a button combination like ```ctrl+c``` to close the opened tab right from the unTab results window, it would be great enhancement.

The user will only have to navigate to the respective tab which they wish to close using the arrow keys and then the highlighted tab would then be closed using the provision provided.
![image](https://user-images.githubusercontent.com/43847978/111495450-6328d880-8765-11eb-8ff6-3a1dfaf1e3fe.png)

**Comment by blenderskool** [comment]
Had this in mind, but this will definitely be a _tricky_ feature as the tab searching is implemented as a plugin and the plugin API does not allow any UI elements to be rendered by a plugin as of now.

Not sure how we can support UI in the plugin API in its current form whilst still keeping it standardized across plugins.
If there's no other plugin that requires this special UI level treatment, then we might integrate tab searching back with the main codebase 😶

Key bindings should be easy to add but may conflict with something on the current webpage. But definitely 👍 for pro-users.

Open to suggestions!

**Comment by blenderskool** [comment]
**Updates:**
- Have been testing UI support for the Plugins API and things look promising. Svelte itself can be used to render controls for various results from the plugins! 🎉 
- Plugins UI **should be used with care** as over-using them may lead to confusion and a bad UX.
- Key binding support is not possible at this moment. Might open another issue to track this separately.
