### ISSUE TITLE
Addition of border for better distinction

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#55]
The unTab window, on some websites might not be distinguishable at all from the background. Example given below :+1: 

![image](https://user-images.githubusercontent.com/43847978/111522268-1c94a780-8780-11eb-9dd0-e76546bebd67.png)

Thus inclusion of a border around the outermost container div would really help distinguish the unTab window from all kinds of background.

**Comment by blenderskool** [comment]
Makes sense, I will experiment with this.
