### ISSUE TITLE
unTab window does not open in previously opened tabs

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#58]
**Steps to replicate the issue**

1. Open a couple of tabs in the web browser (we shall refer to these tabs as `formers`). Make sure that when these tabs are opened, `unTab` isn't added as an extension.
2. Now, add `unTab` as an extension.
3. Open some more tabs now (we shall refer to these as `latters`).

One could notice that upon trying to open the `unTab` window in the `formers` it does not open, however when we try to do the same in `latters` it works fine. What causes this issue?

A request to add the `question` label as welll to this issue.

**Comment by blenderskool** [comment]
The reason for this behaviour is following:
- UnTab extension works by embedding a script on every page you open after it is activated (which let's us show the interface on top of the existing page)
- In case of `formers`, this script does not get added as after UnTab is installed (it does not embed the script on old pages)
- It is important to note that the embedding of script is taken care by the browser itself and it starts embedding the script in tabs opened after the extension is activated (which here is referred to as `latter`)

Hope that clears the question 🙂

**Comment by blenderskool** [comment]
Possible solutions to explore:
- see if we can manually embed script on previously opened tabs(`formers`).
- Check out #48 as it is very relevant to this and might be a reasonable solution considering other pages where this script can't even be embedded.

**Comment by tanishqvyas** [comment]
@blenderskool Thanks a lot for the explanation. That sure helped. I'll take a look at [#48](https://github.com/blenderskool/untab/issues/48).
