### ISSUE TITLE
Plugin for Google Scholar Search

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#59]
The addition of a `/Scholar Search` as a plugin would really save some time while trying to search google scholar for desired results. When looking up research papers, articles, reports, etc students and developers tend to make use of google scholar for refined search results. doing the same would become much faster with the addition of a `/Scholar Search` plugin.

**Comment by blenderskool** [comment]
Little too niche IMO, there are many other general search plugins that can be added prior to this. Eg. Wikipedia

**Comment by blenderskool** [comment]
@tanishqvyas 
> The majority of people who would actually use the unTab extension for boosting their productivity, won't they belong to the group of developers or tech enthusiasts? In that case, the niche would be considered as general by them.

Even in the group of developers and tech enthusiasts, Google Scholar is not something everyone visits on a regular basis. I don't know whether UnTab will improve the workflow for this group of people. Just that, I feel there are other sites which would be of more value than Google Scholar (I might be wrong though, as this totally depends on how one uses the internet)

_If developers are a concern, we should probably provide a StackOverflow search too_ :stuck_out_tongue:

>  If you could assign this issue to me and if I could implement the required functionality then would you be willing to allow this plugin ?

It's not that I'm against the plugin, just that slowly we'll have a search plugin for every site. I was thinking of a more general approach to handle searching similar to how Omnibar does it but seems like it is infeasible at this moment :neutral_face:
