### ISSUE TITLE
Add support to interact with Storage

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#68]
It would be great to type in certain keywords such as `#ls localStorage` and be able to view if there are any `localStorage` items present. The usual way of doing it involves slightly more steps.

A possible way to encode these actions could be to have them in the following format:

```
action entity {entity-identifier}
```

Where action can be : 

* `listing items` (`#ls localStorage`)
* `permanently deleting an item` (`#rm localStorage {key}`)

The entity identifier will be optional since it depends on the use case.

The keywords for actions can be similar to bash commands to keep familiarity. This feature could then be scaled to incorporate things like cookies, session storage, etc.

If possible, these type of commands could have their own dedicated input/tab section where we can type it out. Toggling between the two (commands input and search input) could be provided via some hotkey or if the design could incorporate a visual cue to clearly hint if the input tab is in `search mode` or `commands mode` that would be great.

A possible way to do so could be to replace the `search icon` with an appropriate `command icon` upon the press of the toggle hotkey.

Another possible way could be to hand this just like we handle `plugins`. Once the user enters `/` the tab shows the available plugins. In a similar fashion if the above commands can be shown upon entering `#` then it would be great.

**Comment by blenderskool** [comment]
This seems a very dev-focused feature. In any case, I think the browser dev-tools provide a more intuitive UI to manage most of the browser storage APIs which is easier to understand than what UnTab would be able to provide via these commands.

**Comment by tanishqvyas** [comment]
@blenderskool That indeed is a valid point, given the functionality, the amount of work is necessarily too much for a very niche feature.
