### ISSUE TITLE
Default sort to Most Recently Used tabs

### ISSUE THREAD

**Issue by sinewave** [blenderskool/untab#69]
Really awesome plugin, can't wait to see where you take it!!

One feature request that would really help improve my workflow and use of this extension would be if the default sort, after triggering the extension, was by most recently used. 

Often times I want to switch tabs and I don't remember the title but I do know that I was using it recently, similar to alt-tab.

**Comment by blenderskool** [comment]
This seems quite useful, thanks for the suggestion @sinewave.
I was considering sorting by most active tab #2, but this makes more sense
