### ISSUE TITLE
Unable to use unTab

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#77]
Despite using the unique key combination of `Ctrl+Shift+Space` I am unable to open the unTab window. I have tried to uninstall and re-install the extension again in chrome but unfortunately, I haven't been able to use it. The extension was working fine 3 days ago.

A point to be noted is that I am able to access the `unTab window` after clicking on the icon under my listed extensions. But that kind of defeats the purpose of not using touchpad.

Additionally, I have even tried restarting the browser application. Even that did fix the issue. Could you please let me know how to get it to work again?

**Comment by blenderskool** [comment]
@tanishqvyas Can you check if clicking the UnTab icon in toolbar opens the UnTab interface?

Hotkey does seem to behave in an unstable way for some reason. Will require more understanding on how chrome handles extension hotkeys

**Comment by blenderskool** [comment]
@tanishqvyas Can you go to [chrome://extensions/shortcuts](chrome://extensions/shortcuts) and check if there's an appropriate shortcut assigned to 'toggle-search' event?

**Comment by tanishqvyas** [comment]
@blenderskool This is what I found when I checked in `chrome://extensions/shortcuts`

![image](https://user-images.githubusercontent.com/43847978/139556147-d68ba1cc-029c-4060-8ce9-8e4f807b70d3.png)

**Comment by blenderskool** [comment]
@tanishqvyas you can add the shortcut using the pencil icon next to `toggle-search` event. I don't know when Chrome decides to enable/disable a shortcut, but it seems like re-installing UnTab and restarting Chrome usually fixes it.

Anyone who understands this behavior better, please help!

**Comment by tanishqvyas** [comment]
@blenderskool Adding it manually did fix the issue. Thank you. I would really like to know why chrome behaved this way though.

**Comment by blenderskool** [comment]
Pinning this for more visibility in case anyone faces this issue or has suggestions to fix it.
