### ISSUE TITLE
UX / UI Enhancement for the displayed results

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#78]
Currently, the results that are being displayed, show the `close` and `pin` options always. Would it be possible to display these options only when the option is selected/hovered upon? That would improve the experience and make it look cleaner.

![image](https://user-images.githubusercontent.com/43847978/139541676-33bb40cb-25ed-4b60-bbaa-9a624a5adc57.png)

Building on that, additional useful `action` words can be shown such as `Open Bookmark` at the end of a bookmark result. Which currently is not shown.

![image](https://user-images.githubusercontent.com/43847978/139542355-901d1541-6458-4b55-9eaa-902ff2528b08.png)

**Comment by blenderskool** [comment]
1. It is possible to show them on hover/select, need to experiment if it actually improves the UX.
2. I imagined this to be pretty self-explanatory, but if it isn't, then we may be able to sneak it in somewhere. Beside the result may be difficult as space is limited.

**Comment by blenderskool** [comment]
@tanishqvyas I tested the possibility of showing these buttons only when hovered, and things seem fine for buttons that are stateless, eg. the close button.
For buttons also showing some state information, eg. pinned state, there is **no immediate info** about whether a tab is pinned or not without having to hover each result and observe the button state.

For this reason, I don't think I'll be continuing to add this enhancement right now. If somebody finds this useful or has a different approach in mind, you may re-open this issue for further discussion.
