### ISSUE TITLE
Categories should be stickied during scrolling

### ISSUE THREAD

**Issue by asharonbaltazar** [blenderskool/untab#8]
Right now, it's impossible, at first glance or scrolling back up, to know whether the user is looking at tabs or history. Making the categories stick at the top of the results should help.

I'm not familiar with Svelte, however, for `sticky` to work, there needs to be a `div` surrounding _both_ the category div and the appropriate results.

**Comment by blenderskool** [comment]
Yes, category sticking sounds really useful. I would look into this as we might need some restructuring of markup for this to work.

**Comment by blenderskool** [comment]
This was well-needed, thanks for raising the issue @asharonbaltazar
