### ISSUE TITLE
Customization options for unTab layout and other preferences

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#80]
If we could add a `settings` or `customization` tab where the user could select their preferences for the application, it would be great.

For Example:

Currently `unTab` opens only in a very small portion of my screen. I would highly prefer if I could select between `small`, `medium`, and `large` window sizes for unTab. Such information could be stored at the same place where the preferences for UI themes have been stored.

![image](https://user-images.githubusercontent.com/43847978/139541857-75d18c00-65eb-4566-a8f3-4b9a2f2fa4a1.png)

Other options might include but may not be limited to:

1. Font preference
2. Order of results. Some people might want the history results to appear after bookmarks.

**Comment by blenderskool** [comment]
@tanishqvyas Can you add your comment to #71? This is a similar issue
