### ISSUE TITLE
UI color fixes for scrollbar for standard default theme

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#81]
The highlight color of the result card and the color of the scrollbar are quite similar. Thus, it looks slightly odd when the two are seen along with the result type header.

![image](https://user-images.githubusercontent.com/43847978/139541963-70cad5f4-822f-4f35-8541-b3eabd1bd655.png)

**Comment by blenderskool** [comment]
@tanishqvyas Any suggestions on what color can be used from existing palette? There are various colors specified in a theme, so maybe we can use one of them.

**Comment by blenderskool** [comment]
@tanishqvyas Hope this subtle color looks good 😃 

![](https://user-images.githubusercontent.com/21107799/139554854-04071b04-6297-4885-a098-6873902917a1.png)

**Comment by tanishqvyas** [comment]
@blenderskool It looks great!
