### ISSUE TITLE
Different sizes in different tabs

### ISSUE THREAD

**Issue by tanishqvyas** [blenderskool/untab#82]
The size of the `unTab window` is inconsistent when viewed across different tabs.

**As seen on Github**

![image](https://user-images.githubusercontent.com/43847978/139673460-20be5f4c-aed1-4f3c-b408-38175a0e9c9d.png)

**As seen on Gmail**

![image](https://user-images.githubusercontent.com/43847978/139673528-dfa7382c-1d19-492d-8868-c3039b8ba9d6.png)

Could you please ensure that the sizes across tabs are consistent?

**Comment by blenderskool** [comment]
I don't see any difference in size when on GitHub and Gmail. Perhaps you have different page zoom levels?

**Comment by tanishqvyas** [comment]
@blenderskool Thanks for the quick response. Yes, that is the case. Surprisingly I never realized I was using Gmail in the zoomed manner all along.
